#!/bin/bash

set -eu

FAKEDB="/tmp/checkupdates-db"
rm -rf "$FAKEDB"
mkdir -p "$FAKEDB"

ln -s "/var/lib/pacman/local" "${FAKEDB}/"
fakeroot -- pacman -Sy --dbpath "$FAKEDB" --logfile /dev/null > /dev/null
pacman -Qu --dbpath "$FAKEDB"

rm -rf "$FAKEDB"
