#!/bin/bash

set -e

find /var/abs -type d -name .git -printf '%h\n' | while read d; do
    pushd "$d" > /dev/null
    git fetch
    if [ 0 -ne "$(git diff-index --cached origin/master | wc -l)" ]; then
        echo "$d"
    fi
    popd > /dev/null
done
