#!/bin/bash

set -eu

declare -A pkg_versions
query_url='https://aur.archlinux.org/rpc/?v=5&type=info'

while read pkg installed_version; do
    pkg_versions[$pkg]="$installed_version"
    query_url="${query_url}&arg[]=${pkg}"
done < <(pacman -Qm)

curl -gsSf "$query_url" | jq -r '.results[] | .Name, .Version, "\u0000"' | while read -d $'\0' pkg aur_version; do
    installed_version="${pkg_versions[$pkg]}"
    if [ "$installed_version" != "$aur_version" ]; then
        echo "New ${pkg}: $installed_version -> $aur_version"
    fi
done
