#!/bin/bash

list="
America/Los_Angeles
America/Chicago
America/New_York
Europe/London
UTC
Asia/Ho_Chi_Minh
Australia/Perth
Australia/Sydney
"

for tz in $list; do
    printf "%-25s" "$tz"
    TZ="$tz" date
    echo
done

