#!/bin/bash

set -x

docker container prune -f

docker volume prune -f

docker images --no-trunc --format '{{.ID}} {{.CreatedSince}}' \
    | awk '/ months/ || / years/ { print $1 }' \
    | xargs --no-run-if-empty docker rmi -f

docker image prune -f
