#!/bin/bash

NUM="$(expr 1 + "$(cat current)")"
echo "${NUM}" > current
OUT="$(printf "scan_%04d.jpg" "${NUM}")"

scanimage --progress --mode color --resolution 300dpi --gamma-value 0.999451 > out.pnm
echo "Scanning done..."

tojpeg.py out.pnm "${OUT}" &&
rm -f out.pnm
open "${OUT}"
echo "Written ${OUT}"

