#!/bin/bash

set -e

absdir="$1"
url="$2"
if [ -z "$absdir" -o -z "$url" ]; then
    echo "Usage: $0 absdir url"
    exit 1
fi

unpackdir="${absdir}/unpack"
mkdir -p "$unpackdir"

curl -s "$url" | tar zx --strip-components=1 -C "$unpackdir"
for f in "$unpackdir"/*; do
    diff -u "${absdir}/$(basename "$f")" "$f" || true
done


read -p "Ok? (y/n) " ok
if [ "$ok" != "y" ]; then
    exit 1
fi


mv -v "${unpackdir}"/* "${absdir}/"
rm "${unpackdir}/.SRCINFO"
rmdir "$unpackdir"


(cd "$absdir" && makepkg -i)

