#!/bin/bash

function run_backup {
    rdiff-backup \
        --preserve-numerical-ids \
        --exclude-sockets \
        --exclude '/home/*/tmp' \
        --include '/home' \
        --exclude '/var/cache' \
        --exclude '/var/log' \
        --exclude '/var/tmp' \
        --exclude '/tmp' \
        --include '/var' \
        --exclude-other-filesystems \
        my-host.example.com::/ /backup/my-host

    rdiff-backup -v1 --force --remove-older-than 365D /backup/my-host
}

. /backup/scripts/common

