#!/bin/bash

DISKS="$(grep -Eo '^/dev/[^ ]+' /etc/smartd.conf)"

for dev in $DISKS; do
    name="$(basename "$dev" | sed 's/^ata-//')"
    logfile="/var/log/smart/${name}/$(date +%Y-%m-%d_%H:%M).txt"
    mkdir -p "$(dirname "$logfile")"
    smartctl -a "$dev" > "$logfile"
done

exit 0
