#!/bin/bash

set -eu

hostname="$(basename "$0")"

while true; do
    clear
    echo "Connecting to ${hostname}..."
    ssh \
        -o ServerAliveInterval=1 \
        -o ServerAliveCountMax=5 \
        -t \
        "$@" \
        "$hostname" \
        "bash --login -c 'screen -dR'" \
    && exit 0
    echo "Disconnected, waiting..."
    echo -ne "\\033]0;${hostname}: disconnected!\\007"
    sleep 1
done

