#!/bin/bash

set -eu

if [ -z "${CHRONIC_WRAPPED:-}" ]; then
    export CHRONIC_WRAPPED=1
    exec chronic -e "$0"
fi

. /etc/os-release

function is_distro {
    [ "$ID" = "$1" ] || [ "${ID_LIKE:-}" = "$1" ]
}

if is_distro debian; then
    echo "# aptorphan"
    aptorphan 1>&2
fi

if is_distro arch; then
    echo "# pacorphan"
    pacorphan 1>&2
fi
