#!/bin/bash

set -eu

. /etc/os-release

cd "$(dirname "$(readlink -f "$0")")"

for i in ./*; do
    if [ "$(basename "$i")" != "$(basename "$0")" ]; then
        if ! "$i"; then
            echo -e "\n^^ FAILED! $(hostname) $PRETTY_NAME -- $i ^^\n"
            exit 1
        fi
    fi
done
