#!/bin/bash

. /etc/os-release
. ~/.bashrc

set -eu
cd "$(dirname "$(readlink -f "$0")")"

for i in ./*; do
    if [ "$(basename "$i")" != "$(basename "$0")" ]; then
        if ! "$i"; then
            echo -e "\n^^ FAILED! $(cat /etc/hostname) $PRETTY_NAME -- $i ^^\n"
            exit 1
        fi
    fi
done
