#!/bin/bash

iface="$1"
action="$2"

if [ "$iface" = "ethernet" -a "$action" = "up" ]; then
    nmcli radio wifi off
fi

if [ "$iface" = "ethernet" -a "$action" = "down" ]; then
    nmcli radio wifi on
fi

