#!/usr/bin/env python

import random, string, sys

def generate(length):
	passwd = ""
	for i in xrange(length):
		c = random.choice(string.printable)
		while c.isspace():
			c = random.choice(string.printable)
		passwd += c
	return passwd

if __name__ == "__main__":
	try:
		n = int(sys.argv[1])
	except:
		print "Usage: %s length" % sys.argv[0]
		sys.exit(1)

	print generate(n)




