#!/bin/bash -e
echo -n "Will record in... "
for i in 5 4 3 2 1; do
	echo -n "$i "
	sleep 1
done
echo
echo "Recording now!"

src="$(pactl list | grep -A2 '^Source #' | grep 'Name: .*\.monitor$' | awk '{print $NF}' | tail -n1)"
dest="$1"
shift
parec -d "$src" --rate=44100 --format=s16le --channels=1 /dev/stdout | \
	lame -r -s '44.1' --signed --bitwidth 16 --little-endian -m m "$@" /dev/stdin "$dest"

