#!/bin/bash

FORMAT="%s\n%8s %8s\n\n"
MAILDIRSTAT="maildirstat.py"

if [ -z "${1}" ]; then
	echo "Usage: ${0} mailbox1 [mailbox2 ...]"
	exit 1
fi

for mailbox in "$@"; do
	"${MAILDIRSTAT}" "${mailbox}" "${FORMAT}" 2> /dev/null
done

